OUTPUT_DIR: ""
DATA:
  TRAIN:
    ROOT_DIR: ""
    NUM_VIRTUAL_PLANE:
    INTER_SCALE: 4.24
  VAL:
    ROOT_DIR: ""
  TEST:
    ROOT_DIR: ""
    NUM_VIEW: 
    IMG_HEIGHT: 960
    IMG_WIDTH: 1280
    NUM_VIRTUAL_PLANE:
    INTER_SCALE: 2.13
    MODE: "dtu"
  NUM_WORKERS: 0
MODEL:
  EDGE_CHANNELS: (32, 32, 64)
  TRAIN:
    IMG_SCALES: (0.25, 0.5)
    INTER_SCALES: (0.75, 0.375)
  TEST:
    IMG_SCALES: (0.25, 0.5)
    INTER_SCALES: (0.75, 0.15)
SCHEDULER:
  TYPE: "StepLR"
  INIT_EPOCH: 6
  MAX_EPOCH: 18
  StepLR:
    gamma: 0.9
    step_size: 2
SOLVER:
  BASE_LR: 0.0008
  WEIGHT_DECAY: 0.002
  TYPE: 'RMSprop'
TRAIN:
  BATCH_SIZE: 16
  CHECKPOINT_PERIOD: 1
  LOG_PERIOD: 10
  VAL_PERIOD: 1
TEST:
  WEIGHT: ""
  BATCH_SIZE: 1


